# Logging level (debug, info, warning, error)
logging: info

# Working directory
work_dir: /path/to/workdir

# Timeout for the dumping of decrypted libraries on iOS
dump_timeout: 30

# Timeout of dynamic analysis per app
dynamic_analysis_timeout: 30

# Timeout between installing an iOS app and starting dynamic analysis
# We wait some time after installing the app so background network traffic can finish
dynamic_analysis_ios_start_timeout: 120

# Timeout and memory limit for radare2 analysis of individual binary files
radare_timeout: 120
radare_memory_limit: 8 # GB

# Radare2 hosts to use for static analysis
# 'local' / 'localhost' will run on the local machine
# Other hosts will use ssh to log into the machine and run radare2 there
# The number after the host indicates the maximum number of radare2 instances to run on that machine at once
radare_servers: 
  local: 2
  user@example.com: 4

# Will uninstall the app after downloading the app to the device or performing dynamic analysis
# The analyzer re-install the app via the binaries stored in the working directory or from the app store when needed
# Setting this to false may cause errors when installing many apps at the same time because of full device storage
uninstall_apps: True

# Login information for the Google Play Store to automatically download apk files
# Can be obtained by e.g. using this app: https://github.com/whyorean/Authenticator/releases/
# It is important to run the app on the same device as the dynamic test, since it determines the binaries that are downloaded of split apks
# Also, keep in mind that this token is region specific, so if you are using a proxy, make sure it is in the same country as the device
play_store_email: mail@example.com
play_store_aastoken: aas_et/AKppIN...

# Login information for the Apple App Store to automatically download ipa files
app_store_email: mail@example.com
app_store_password: password

# ABI / architecture of the device used for dynamic analysis
# The framework will only run static analysis on binaries for this ABI to save time
android_abi: arm64-v8a

# Apps to download / analyze
apps:
  android:
    - com.whatsapp
    - com.instagram.android
    - com.facebook.katana
  ios: []

# Devices to use for dynamic analysis.
# Name is used to identify the device. If stealth root is used, include this in the name.
# Serial is the serial number of the device. For emulators, this is typically emulator-5554. Use adb devices to find the serial number.
# Type is the type of device. Options are emulator, root, and physical.
# OS is the operating system of the device. Options are android and ios.
# IP is the IP address of the device. This is used for network communication.
# Network adapter is the network adapter of the device. This is used for network communication.
# Snapshot is the name of the snapshot to restore on the emulator. This is used to reset the emulator to a clean state.
# AVD is the name of the AVD to use for the emulator. This is used to start the emulator with the correct configuration.
devices:
  - name: device1
    serial: emulator-5554
    type: emulator
    os: android
    ip: 192.168.0.2
    network_adapter: tap0
    snapshot: fresh_wiped_frida
    avd: haly_11_x86_google
  - name: device2
    serial: serial2
    type: root
    os: android
    ip: 192.168.0.3
    network_adapter: wlan0
