# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test Swift
  pod "Alamofire", "5.6.4" 

  target 'Test SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Test SwiftUITests' do
    # Pods for testing
  end

end
